### ISSUE TITLE
 startReading(),  stopReading()

### ISSUE THREAD

**Issue by jaidiwael** [paulobunga/c72-rfid-scanner#1] opened 2020-05-04 13:13 UTC
Thank you for creating this repo,
I followed the process Usage  when i click  startReading() i got False, and  stopReading i got 0.

Thank you
<img width="819" alt="Screen Shot 2020-05-04 at 11 36 18 AM" src="https://user-images.githubusercontent.com/2828788/80969380-6b0fb080-8e11-11ea-9831-73a0724b60ca.png">

**Comment by paulobunga** [comment] 2020-05-05 11:48
Read power had to read 1. Make sure you initialize the device first. You can do that when you mount the root component

**Comment by paulobunga** [comment] 2020-05-08 18:45
This issue was caused by incompatible deviceApi in some C72 Scanners. upgrading this API fixed the issue. Closing this issue now.

**Closed as completed by paulobunga** 2020-05-08 18:45 UTC
